### ISSUE TITLE
option name & npm warning

### ISSUE THREAD

**Issue by rexkenley** [OliverFlint/XrmTypesGen#22]
1. The /tenent switch should be /tenant
2.  Getting a warning during install
![image](https://user-images.githubusercontent.com/10548251/171871217-708f7da4-5e38-43d0-b8a9-a5d746a254c0.png)

*I found this article and wanted to get your thoughts on the claim

**The first thing to be aware of is that @types/xrm and XrmDefinitelyTyped are incompatible with each other. You cannot have the DefinitelyTyped type definitions in the same compilation context as the XrmDefinitelyTyped definitions.**

https://dyncrmexp.com/2020/06/28/modern-web-resource-workspace-in-dynamics-365-part-2-declaration-files/comment-page-1/

**Comment by OliverFlint** [comment]
Well, the fact the @types/xrm and XrmDefinitelyTyped are not compatible is one of my main drivers for this project! It was my first issue with XrmDefinitelyTyped, when I have a project that already uses @types/xrm, migrating to XrmDefinitelyTyped wasn't as straightforward as it could have been, so, I created this project so I could have the coolness of XrmDefinitelyTyped and not have the pain of having to migrate the code and tests to the new typings.

**Comment by OliverFlint** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [a thing](https://trello.com/c/CNr0mZrp/1-a-thing)
